<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- 単一ファイル発行設定 -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <IncludeNativeLibrariesForSelfContained>true</IncludeNativeLibrariesForSelfContained>
    <IncludeAllContentForSelfContained>true</IncludeAllContentForSelfContained>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Icon_show_light.ico" />
    <EmbeddedResource Include="Icon_hide_light.ico" />
    <EmbeddedResource Include="Icon_show_dark.ico" />
    <EmbeddedResource Include="Icon_hide_dark.ico" />
  </ItemGroup>

</Project>